configurator/company/urls.py
from django.urls import path
from . import views

app_name = 'company'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

configurator/configurator/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("django.contrib.auth.urls")),
    path('profile/', include('profiles.urls', namespace="profile")),
    path('company/', include('company.urls', namespace="company")),
    path('product/', include('product.urls', namespace="product")),
    path('', RedirectView.as_view(url='company/', permanent=True)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

configurator/product/urls.py
from django.urls import path
from . import views

app_name = 'product'
urlpatterns = [
    path('', views.index, name='index'),
    path('configurator/', views.configurator, name='configurator'),
    path('manually/', views.manually, name='manually'),
    path('box/', views.box, name='box'),
]

configurator/profiles/urls.py
from django.urls import path
from . import views

app_name = 'profile'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('signin/', views.signin, name='signin'),
    path('drafts/', views.drafts, name='drafts'),
    path('logout/', views.log_out, name='log_out'),
]

configurator/product/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models

def validate_range(value):
    if value < 0 or value > 200:
        raise ValidationError(f"Value must be between 0 and 200. Given: {value}")


# Create your models here.
class Material(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    material_components = models.TextField()                           # Material components (long text)
    thickness = models.FloatField(default=1.0)                                    # Thickness as a float

    def __str__(self):
        return self.name


class Component(models.Model):
    id = models.AutoField(primary_key=True)
    material_id = models.ForeignKey(
        Material,
        on_delete=models.CASCADE                              # Cascade delete related records
    )
    width = models.FloatField()
    height = models.FloatField()
    length = models.FloatField()

    def __str__(self):
        return f"Component {self.id} (Material: {self.material_id})"


class Instruction(models.Model):
    id = models.AutoField(primary_key=True)
    steps = models.TextField()

    def __str__(self):
        return f"Instruction {self.id}"


class Product(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    instruction_id = models.ForeignKey(
        Instruction,
        on_delete=models.SET_NULL,                        # Allows null if instruction is deleted
        null=True,                                         # Enables null values
        related_name='products_with_instruction'          # Optional: for reverse query
    )

    def __str__(self):
        return self.name


class ProductComponent(models.Model):
    product_id = models.ForeignKey(                      # Foreign Key to Product
        Product,                                    # Replace with the actual Product model name
        on_delete=models.CASCADE                      # Cascade delete
    )
    component_id = models.ForeignKey(                   # Foreign Key to Component
        Component,                                 # Replace with the actual Component model name
        on_delete=models.CASCADE                     # Cascade delete
    )
    quantity = models.PositiveIntegerField()         # Quantity as a positive integer

    def __str__(self):
        return f"{self.quantity} of Component {self.component_id} for Product {self.product_id}"


class Draft(models.Model):
    id = models.AutoField(primary_key=True)  # PK
    body_height = models.FloatField(null=True)             # Body height
    stand_height = models.FloatField()            # Stand height
    sitting_height = models.FloatField()
    width = models.FloatField()                   # Width
    length = models.FloatField()                  # Length
    material = models.ForeignKey(
        Material,
        on_delete=models.CASCADE
    )                                             # FK to Material
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE
    )                                             # FK to Product
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )
    quantity = models.PositiveIntegerField()

    def __str__(self):
        return f"Draft {self.id}"

class Box(models.Model):
    id = models.AutoField(primary_key=True)
    box_height = models.FloatField(validators=[validate_range])
    box_length = models.FloatField(validators=[validate_range])
    box_depth =  models.FloatField(validators=[validate_range])

    material = models.ForeignKey(
        Material,
        on_delete=models.CASCADE
    )  # FK to Material
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE
    )  # FK to Product
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )
    quantity = models.PositiveIntegerField()

    def __str__(self):
        return f"Box {self.id}"

configurator/product/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt

from .models import Draft, Material, Product, Box


# Create your views here.
def index(request):
    """View function for home page of site."""

    context = {}

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'product/index.html', context=context)


@csrf_exempt
def manually(request):
    context = {}
    """View function for login page of site."""
    if request.method == 'POST':
        desk_height = float(request.POST.get("manualDeskHeight"));
        stand_height = desk_height *1.3;
        draft = Draft(
            stand_height=stand_height,  # Stand height
            sitting_height=desk_height,  # Sitting height
            width=request.POST.get("manualDeskDepth"),  # Width
            length=request.POST.get("manualDeskLength"),
            body_height=None,
            material_id=1,  # wood
            product_id=1,  # table
            user_id=request.user.id,
            quantity=request.POST.get("quantity"),

        )
        draft.save()
        return render(request, 'product/draft_saved.html', context=context)

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'product/configurator.html', context=context)


@csrf_exempt
def configurator(request):
    context = {}
    if request.user.is_authenticated:
        """View function for login page of site."""
        if request.method == 'POST':
            body_height = float(request.POST.get("inputBodyHeight"))
            standingHeight = 0.125 * 5 * body_height
            sittingHeight = 0.125 * 3.5 * body_height

            draft = Draft(
                body_height=float(request.POST.get("inputBodyHeight")),  # Body height
                stand_height=standingHeight,  # Stand height
                sitting_height=sittingHeight,  # Sitting height
                width=request.POST.get("depth"),  # Width
                length=request.POST.get("length"),
                material_id=1,  # wood
                product_id=1,  # table
                user_id=request.user.id,
                quantity=request.POST.get("quantity"),
            )
            draft.save()
            return render(request, 'product/draft_saved.html', context=context)

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'product/configurator.html', context=context)


@csrf_exempt
def box(request):
    context = {}
    if request.user.is_authenticated:
        """View function for login page of site."""
        if request.method == 'POST':
            box = Box(
                box_height=request.POST.get("box_height"),  # Sitting height
                box_length=request.POST.get("box_length"),  # Width
                box_depth=request.POST.get("box_depth"),
                material_id=1,  # wood
                product_id=2,  # table
                user_id=request.user.id,
                quantity=request.POST.get("quantity"),
            )
            box.save()
            return render(request, 'product/draft_saved.html', context=context)

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'product/box.html', context=context)

configurator/product/templates/product/configurator.html
{% extends 'company/base.html' %}
{% block content %}
{% load static %}

<div class="container" style="padding: 5%;">
    <div class="container" style="text-align: left; padding-bottom: 2%;">
        <h2 class="h2" style="font-weight: bold;font-size: 32px;">Flexi Table</h2>
        <!-- Slogan im gleichen grauen Farbton wie der Infotext -->
        <p style="color: #a47551af;  font-size: 20px;">The perfect balance of durability, flexibility, and
            style for your workspace.</p>
    </div>
    {% if user.is_authenticated %}
    <!-- Configurator Section -->
    <div class="container" style="display: flex; justify-content: space-between; padding-top: 3%; padding-bottom: 5%;">
        <!-- Boxen nach oben verschoben -->
        <!-- Form Section on the Left -->
        <div class="col-6" style="max-width: 48%; padding-right: 5%;">
            
            <!-- Option to Choose Configuration Mode -->
            <div class="form-group">
                <label for="configMode"><strong>Choose Configuration Mode:</strong></label>
                <select class="form-control" id="configMode" onchange="toggleConfigMode()">
                    <option value="calculator">Use Desk Height Calculator</option>
                    <option value="manual">Enter Desk Values Manually</option>
                </select>
            </div>

            <!-- Manual Input Mode -->
            <div id="manualMode" style="display: none;">
                <form action="{% url 'product:manually' %}" method="post" name="TableManuallyDraft"
                      id="TableManuallyDraft">
                    <div class="form-group">
                        <label for="manualDeskHeight"><strong>Desk Height (cm)</strong></label>
                        <input type="number" class="form-control" id="table" name="manualDeskHeight"
                               placeholder="Enter desk height in cm" required min="40" max="160">
                    </div>
                    <div class="form-group">
                        <label for="manualDeskDepth"><strong>Desk Depth (cm)</strong></label>
                        <input type="number" class="form-control" id="table" name="manualDeskDepth"
                        placeholder="Enter desk depth in cm" required min="40" max="200">
                    </div>
                    <div class="form-group">
                        <label for="manualDeskLength"><strong>Desk Length (cm)</strong></label>
                        <input type="number" class="form-control" id="table" name="manualDeskLength"
                               placeholder="Enter desk length in cm" required min="40" max="200">
                    </div>
                    <div class="form-group">
                        <label class="label" for="table">Quantity</label>
                        <input type="number" class="form-control" id="table" name="quantity"
                               placeholder="Enter quantity" required min="1">
                    </div>
                    <button type="submit" value="Submit" class="btn btn-save">Save Draft</button>
                </form>
            </div>

            <!-- Calculator Mode -->
            <div id="calculatorMode" style="display: none;">
                <form action="{% url 'product:configurator' %}" method="post" name="TableDraft" id="TableDraft">
                    <div class="form-group">
                        <label class="label" for="table">Your Body Height (cm)</label>
                        <input type="number" class="form-control" id="table" name="inputBodyHeight"
                               placeholder="Enter body height in cm" required min="100" max="220">
                    </div>
                    <div class="form-group">
                        <label class="label" for="table">Desk Length (cm)</label>
                        <input type="number" class="form-control" id="table" name="length"
                               placeholder="Enter length in cm" required min="40" max="200">
                    </div>
                    <div class="form-group">
                        <label class="label" for="table">Desk Depth (cm)</label>
                        <input type="number" class="form-control" id="table" name="depth"
                               placeholder="Enter depth in cm" required min="40" max="200">
                    </div>
                    <div class="form-group">
                        <label class="label" for="table">Quantity</label>
                        <input type="number" class="form-control" id="table" name="quantity"
                               placeholder="Enter quantity" required min="1">
                    </div>
                    <button type="submit" value="Submit" class="btn btn-save">save draft</button>
                </form>
            </div>
            
        </div>
        <!-- Image Section -->
        <div style="max-width: 48%; padding-left: 5%; text-align: center;margin-top: 5px">
            <!-- Large Image -->
            <div style="position: relative;">
                <img id="largeImage" src="{% static 'product/Tisch 1.jpg' %}"
                     class="rounded"
                     style="width: 100%; max-width: 400px; height: 300px; object-fit: contain;"
                     alt="Large Box Image">
                <!-- Next Arrow Button -->
                <button id="nextImageBtn"
                        style="position: absolute; top: 40%; right: 10px; transform: translateY(-50%);
                           color: #a47551af;
                           padding: 10px; font-size: 24px; background-color: transparent; border: none;
                           cursor: pointer; transition: all 0.3s ease;">
                    →
                </button>
                <!-- Thumbnail Navigation -->
                <div style="display: flex; justify-content: center; gap: 10px; padding-top: 20px;">
                    <img src="{% static 'product/Tisch 1.jpg' %}" class="thumbnail"
                         onclick="changeImage(this.src)"
                         style="width: 20%; max-width: 80px; height: 60px; object-fit: contain; cursor: pointer;"
                         alt="Thumbnail 1">
                    <img src="{% static 'product/Tisch 2.jpg' %}" class="thumbnail"
                         onclick="changeImage(this.src)"
                         style="width: 20%; max-width: 80px; height: 60px; object-fit: contain; cursor: pointer;"
                         alt="Thumbnail 2">
                    <img src="{% static 'product/Tisch 3.jpg' %}" class="thumbnail"
                         onclick="changeImage(this.src)"
                         style="width: 20%; max-width: 80px; height: 60px; object-fit: contain; cursor: pointer;"
                         alt="Thumbnail 3">
                    <img src="{% static 'product/Tisch 4.jpg' %}" class="thumbnail"
                         onclick="changeImage(this.src)"
                         style="width: 20%; max-width: 80px; height: 60px; object-fit: contain; cursor: pointer;"
                         alt="Thumbnail 4">
                    <img src="{% static 'product/TischMasskette.jpg' %}" class="thumbnail"
                         onclick="changeImage(this.src)"
                         style="width: 20%; max-width: 80px; height: 60px; object-fit: contain; cursor: pointer;"
                         alt="Thumbnail 5">


                </div>
            </div>
        </div>
        <script>
            // JavaScript for Thumbnail Click
            function changeImage(src) {
                document.getElementById('largeImage').src = src;
            }

            // JavaScript for Next Button
            let currentIndex = 0;
            const imageSources = [
                "{% static 'product/Tisch 1.jpg' %}",
                "{% static 'product/Tisch 2.jpg' %}",
                "{% static 'product/Tisch 3.jpg' %}",
                "{% static 'product/Tisch 4.jpg' %}",
                "{% static 'product/TischMasskette.jpg' %}"
            ];

            document.getElementById('nextImageBtn').addEventListener('click', () => {
                currentIndex = (currentIndex + 1) % imageSources.length; // Cycle through images
                document.getElementById('largeImage').src = imageSources[currentIndex];
            });
        </script>
    </div>
</div>

<div class="container" style="text-align: left; padding-bottom: 2%; width: 80%;">
    <h2 class="h2" style="font-weight: bold;font-size: 20px;">Description</h2>
    <!-- Slogan im gleichen grauen Farbton wie der Infotext -->
    <p style="color: #a47551af;  font-size: 20px;">The Flexi Table Configurator allows you to design a table perfectly
        suited to your body size, ensuring better ergonomics, comfort, and productivity in your workspace.
        <br><br> There are two options, either <u>to configure the table based on your body height</u> for two
        positions, the standard sitting position and the standing position. The software will calculate the most optimal
        and ergonomic table height for both positions based on your height. It is also possible to <u>manually configure
            the table by such parameters as length, depth and height</u>.
        <br><br>The main advantages of the table are its relatively cheap and fast production, which can be carried out
        anywhere in the world. Not only wood can be used as the main material, but also plastic or corrugated cardboard
        reinforced with mdf boards. In addition, such a table is easy enough to make at home with the necessary
        materials, tools and instructions.
        <br><br>In future improvements to the website, a function to select the target audience will be added because
        the target audience of flexi is not only private customers, but also schools, universities and other educational
        institutions. As it would be more logical for a university to create the appropriate number of students for a
        range of heights at once. as well as choose colours for the size scale that helps with faster visual search.
    </p>
</div>
{% else %}
    <!-- If the user is not logged in, show an error message -->
    <div style="margin-top: 20px; margin-bottom: 10%; padding: 20px; border: 1px solid #a47551af; background-color: #f9f9f900; border-radius: 10px; color: #A47551;">
        <strong>Error:</strong> You must be logged in to configure and save drafts.
        <a href="{% url 'login' %}" class="btn btn-save" style="margin-left: 10px;">log in</a>
    </div>
    {% endif %}



<script>
    // Funktion zum Wechseln des Bildes durch Klicken auf die Thumbnails
    function changeImage(src) {
        document.getElementById('largeImage').src = src;
    }

    // Funktion zum Wechseln des Bildes nach rechts
    function nextImage() {
        const images = [
            "{% static 'product/Tisch 1.jpg' %}",
            "{% static 'product/Tisch 2.jpg' %}",
            "{% static 'product/Tisch 3.jpg' %}",
            "{% static 'product/Tisch 4.jpg' %}"
        ];

        const currentImage = document.getElementById('largeImage').src.split('/').pop(); // Nur den Dateinamen extrahieren
        let currentIndex = images.indexOf(`{% static 'product/${currentImage}' %}`);

        if (currentIndex === images.length - 1) {
            currentIndex = -1; // Gehe zurück zum ersten Bild
        }

        document.getElementById('largeImage').src = images[currentIndex + 1];
    }
</script>

<script>
    // Toggle between calculator and manual input
    function toggleConfigMode() {
        const mode = document.getElementById("configMode").value;
        if (mode === "calculator") {
            document.getElementById("calculatorMode").style.display = "block";
            document.getElementById("manualMode").style.display = "none";
        } else {
            document.getElementById("calculatorMode").style.display = "none";
            document.getElementById("manualMode").style.display = "block";
        }
    }

    // Initialize the configuration mode on page load
    document.addEventListener("DOMContentLoaded", function () {
        toggleConfigMode(); // Ensure the correct mode is displayed
    });
</script>

{% endblock %}

configurator/product/templates/product/draft_saved.html
{% extends 'company/base.html' %}
{% block content %}
{% load static %}

<div class="container" class="container" style="padding: 5%; display: flex; align-items: center; justify-content: space-between; font-family: 'Helvetica Neue', sans-serif; color: #7A9E7E;">
    <!-- Textbereich -->
    <div style="flex: 1; max-width: 60%; padding-right: 20px;">
        <h1 style="font-size: 32px; font-weight: bold; color: #7A9E7E;">Draft successfully saved.</h1>
        <h3 style="font-size: 20px; font-weight: normal; color: #7A9E7E;">Thank you very much for your interest in our product.</h3>
        <h4 style="font-size: 20px; font-weight: normal; margin-top: 20px; line-height: 1.8; color: #A47551;">
            Would you like to review your draft? You can find your drafts in your
            <a href="{% url 'profile:drafts' %}" style="color: #A47551; text-decoration: underline;">profile</a>.
        </h4>
    </div>

    <!-- Bildbereich -->
    <div style="flex: 1; max-width: 45%; text-align: center;">
        <img src="{% static 'company/IMG_0721.png' %}" alt="Decorative Image" style="width: 80%;">
    </div>
</div>

{% endblock %}

configurator/product/templates/product/index.html
{% extends 'company/base.html' %}
{% block content %}
{% load static %}
<div class="container" style="padding: 5% 5%;">

    <div class="text-center" style="margin-bottom: 4%;">
        <h2 class="h2" style="font-weight: bold; margin-bottom: 10px; font-size: 32px;">Our Flexi Products</h2>
        <p style="font-size: 20px; color: #a47551af; ">Discover smart solutions tailored to your needs</p>
    </div>


    <div class="row" style="margin-bottom: 4%;">
        <div class="col-6 text-center" style="position: relative;">
            <img src="{% static 'product/box-index.jpg' %}" alt="Flexi Connectable Boxes" style="width: 100%; max-height: 300px; object-fit: cover;">
            <h2 style="font-size: 24px; font-weight: bold; margin-top: 5%;">
                <a href="{% url 'product:box' %}" style="color: #7A9E7E; text-decoration: underline;">Flexi Connectable Boxes</a>
            </h2>
        </div>
        <div class="col-6 text-center" style="position: relative;">
            <img src="{% static 'product/table-index.png' %}" alt="Flexi Table Configurator" style="width: 100%; max-height: 300px; object-fit: cover;">
            <h2 style="font-size: 24px; font-weight: bold; margin-top: 5%;">
                <a href="{% url 'product:configurator' %}" style="color: #7A9E7E; text-decoration: underline;">Flexi Table Configurator</a>
            </h2>
        </div>
    </div>

    <!--
    <div class="container row">
        <div class="col-6" style="text-align: center;">
            <h2 style="font-size: 24px; font-weight: bold; color: #6A5D4D; margin-bottom: 10px;">
                <a href="{% url 'product:box' %}" style="color: #7A9E7E; text-decoration: underline;">Flexi Connectable Boxes</a>
            </h2>
            <p style="font-size: 18px; color: #A47551; max-width: 700px; margin: auto;">
                Flexi Connectable Boxes are designed for maximum adaptability and flexibility. Whether you're organizing your home, office, or workshop, our connectable boxes can be easily combined and stacked to create customized storage solutions.
            </p>
            <p style="font-size: 16px; color: #7D6B5F; margin-top: 10px;">✓ Modular design ✓ Eco-friendly ✓ Easy to stack</p>
        </div>
        <div class="col-6" style="text-align: center;">
            <h2 style="font-size: 24px; font-weight: bold; color: #6A5D4D; margin-bottom: 10px;">
                <a href="{% url 'product:configurator' %}" style="color: #7A9E7E; text-decoration: underline;">Flexi Table Configurator</a>
            </h2>
            <p style="font-size: 18px; color: #A47551; max-width: 700px; margin: auto;">
                The Flexi Table Configurator allows you to design a table perfectly suited to your body size, ensuring better ergonomics, comfort, and productivity in your workspace.
            </p>
            <p style="font-size: 16px; color: #7D6B5F; margin-top: 36px;">✓ Customizable height ✓ Durable materials ✓ Foldable design</p>
           
        </div>
    </div>

    <hr style="width: 50%; border: none; border-top: 1px solid #D9C9B9; margin: 2% auto;">


    <div class="text-center" style="margin-bottom: 5%;">
        <h2 style="font-size: 26px; font-weight: bold; color:#A47551; margin-bottom: 10px;">Ergonomics & Health</h2>
        <p style="font-size: 18px; color: #A47551; max-width: 700px; margin: auto;">
            Poor sitting habits can lead to long-term health issues, including back pain and decreased productivity. Flexi products are designed to encourage correct posture, improve ergonomics, and support a healthier lifestyle.
        </p>
    </div>

    <div class="text-center">
        <h2 style="font-size: 26px; font-weight: bold; color: #A47551; margin-bottom: 10px;">Sustainable Materials</h2>
        <p style="font-size: 18px; color: #A47551; max-width: 700px; margin: auto;">
            Our products are made from durable, eco-friendly materials, ensuring longevity while reducing environmental impact. Sustainability meets functionality with Flexi.
        </p>
    </div>
    -->
</div>
{% endblock %}