configurator/company/urls.py
from django.urls import path
from . import views

app_name = 'company'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

configurator/configurator/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("django.contrib.auth.urls")),
    path('profile/', include('profiles.urls', namespace="profile")),
    path('company/', include('company.urls', namespace="company")),
    path('product/', include('product.urls', namespace="product")),
    path('', RedirectView.as_view(url='company/', permanent=True)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

configurator/profiles/urls.py
from django.urls import path
from . import views

app_name = 'profile'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('signin/', views.signin, name='signin'),
    path('drafts/', views.drafts, name='drafts'),
    path('logout/', views.log_out, name='log_out'),
]

configurator/profiles/models.py
from django.db import models
from django.contrib.auth.models import User


class Customer(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.TextField()                     # Address field for longer text
    created_at = models.DateTimeField(auto_now_add=True) # Automatically set on creation
    updated_at = models.DateTimeField(auto_now=True)     # Automatically update on modification

configurator/profiles/views.py
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import authenticate, logout
from django.contrib.auth import login as auth_login
from django.contrib import messages
from django.contrib.auth.models import User

from product.models import Draft, Material, Box
from profiles.models import Customer


# Create your views here.
def index(request):
    """View function for home page of site."""
    context = {}
    if request.user.is_authenticated:
        name = User.get_full_name(request.user)
        address = Customer.objects.get(user=request.user.id).address
        print(name, address)
        context["name"] = name
        context["address"] = address
        return render(request, 'profiles/profile.html', context=context)

    # Redirect to login page if not authenticated
    return redirect("/profile/login")


@csrf_exempt
def login(request):
    """View function for login page of site."""
    context = {}
    if request.method == 'POST':
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            auth_login(request, user)
            return redirect("/profile/")

    # Render the login page
    return render(request, 'profiles/login.html', context=context)


def log_out(request):
    """View function to log out a user."""
    if request.user.is_authenticated:
        logout(request)
    return redirect('/profile/')


@csrf_exempt
def signin(request):
    """View function for signin page of site."""
    context = {}
    if request.method == 'POST':
        username = request.POST["username"]

        if User.objects.filter(username=username).exists():
            messages.error(request, "Username already exists")
            return redirect("login")

        email = request.POST["email"]
        password = request.POST["password"]
        first_name = request.POST["name"]
        last_name = request.POST["surname"]
        new_user = User.objects.create_user(
            username=username, email=email, password=password,
            first_name=first_name,
            last_name=last_name,
        )
        new_user.save()
        messages.success(request, "Account created successfully!")

        address = request.POST["address"]
        customer = Customer.objects.create(user=new_user, address=address)
        customer.save()

        auth_login(request, new_user)
        return redirect("/profile/")

    # Render the signin page
    return render(request, 'profiles/signin.html', context=context)


def drafts(request):
    """View function for drafts page of site."""
    if request.user.is_authenticated:
        """Data from database for the tables"""
        drafts = Draft.objects.filter(user=request.user).order_by('-id')[:10]

        idx = [r['id'] for r in drafts.values()]
        bh = [r['body_height'] for r in drafts.values()]
        sth = [r['stand_height'] for r in drafts.values()]
        sh = [r['sitting_height'] for r in drafts.values()]
        w = [r['width'] for r in drafts.values()]
        l = [r['length'] for r in drafts.values()]
        mat = [Material.objects.get(id=r['material_id']) for r in drafts.values()]
        q = [r['quantity'] for r in drafts.values()]

        draft_items = zip(bh, sth, sh, w, l, mat, q)

        """Data from database for the boxes"""
        boxes = Box.objects.filter(user=request.user).order_by('-id')[:10]

        idx = [r['id'] for r in boxes.values()]
        bxh = [r['box_height'] for r in boxes.values()]
        bxl = [r['box_length'] for r in boxes.values()]
        bxd = [r['box_depth'] for r in boxes.values()]
        mat = [Material.objects.get(id=r['material_id']) for r in boxes.values()]
        q = [r['quantity'] for r in boxes.values()]

        box_items = zip( bxh, bxl, bxd, mat, q)

        """data for the template"""
        context = {'draft_items': draft_items, 'box_items': box_items}

        # Render the drafts page
        return render(request, 'profiles/drafts.html', context=context)
    else:
        return redirect("/profile/login")


def box(request):
    """View function for displaying box drafts."""
    if request.user.is_authenticated:
        boxes = Box.objects.filter(user=request.user).order_by('-id')[:10]

        idx = [r['id'] for r in boxes.values()]
        bh = [r['box_height'] for r in boxes.values()]
        sth = [r['box_length'] for r in boxes.values()]
        sh = [r['box_depth'] for r in boxes.values()]
        mat = [Material.objects.get(id=r['material_id']) for r in boxes.values()]
        q = [r['quantity'] for r in boxes.values()]

        box_items = zip( bh, sth, sh, mat, q)
        context = {'box_items': box_items}

        # Render the box drafts page
        return render(request, 'profiles/drafts.html', context=context)
    else:
        return redirect("/profile/login")

configurator/profiles/templates/profiles/drafts.html
{% extends 'company/base.html' %}
{% block content %}

<div class="container" style="padding: 5%;">
    <div class="container" style="text-align: center; padding-bottom: 3%;">
        <h2 class="h2" style="font-size: 32px;">Your saved drafts for <span class="highlight" style="color:#7A9E7E;">FlexiBox</span> </h2>
    </div>
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">Box Height</th>
            <th scope="col">Box Length</th>
            <th scope="col">Box Depth</th>
            <th scope="col">Material</th>
            <th scope="col">Quantity</th>

        </tr>
        </thead>
        <tbody>
        {% for bxh, bxl, bxd, mat, q in box_items%}
        <tr>
            <td scope="row">{{ bxh }}</td>
            <td>{{ bxl }}</td>
            <td>{{ bxd }}</td>
            <td>{{ mat }}</td>
            <td>{{ q }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    
</div>

<div class="container" style="padding: 0% 5% 5% 5%;">
    <div class="container" style="text-align: center; padding-bottom: 3%;">
        <h2 class="h2" style="font-size: 32px;">Your saved drafts for <span class="highlight" style="color:#7A9E7E;"> FlexiTable</span> </h2>
    </div>
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">Body Height</th>
            <th scope="col">Stand Height</th>
            <th scope="col">Sitting Height</th>
            <th scope="col">Depth</th>
            <th scope="col">Length</th>
            <th scope="col">Material</th>
            <th scope="col">Quantity</th>

        </tr>
        </thead>
        <tbody>
        {% for bh, sth, sh, w, l, mat, q in draft_items%}
        <tr>
            <td scope="row">{{ bh }}</td>
            <td>{{ sth }}</td>
            <td>{{ sh }}</td>
            <td>{{ w }}</td>
            <td>{{ l }}</td>
            <td>{{ mat }}</td>
            <td>{{ q }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>


{% endblock %}

configurator/profiles/templates/profiles/login.html
{% extends 'company/base.html' %}
{% block content %}

<head>
    <title>Flexi Login</title>
</head>


<div class="container" style="padding: 5%; padding-bottom: 10%;">
    <div class="container row">
        <div class="col-6" style="padding-right: 5%;">
            <div class="container" style="text-align: left; padding-bottom: 3%;">
                <h2 class="h2" style="font-size: 32px;">Log In</h2>
            </div>
            <div class="container" style="padding-right: 10%;">
                <form action="{% url 'profile:login' %}" method="post" name="login" id="login">
                    <div class="form-group">
                        <label class="label" for="login">Username</label>
                        <input type="int" class="form-control" id="login" name="username" placeholder="Username" required>
                    </div>
                    <div class="form-group">
                        <label class="label" for="login">Password</label>
                        <input type="int" class="form-control"  id="login" name="password" placeholder="Password" required>
                    </div>
                    <button type="submit" value="Submit" class="btn btn-save">log in</button>
                </form>
            </div>
        </div>
        <div class="col-6" style="padding-right: 5%;">
            <div class="container" style="text-align: left; padding-bottom: 3%;">
                <h2 class="h2" style="font-size: 32px;">New to <span class="highlight" style="color:#7A9E7E;">Flexi</span></h2>
                <p style="font-size: 20px; color: #A4755180; padding-top: 3%; padding-bottom: 3%;">Create a Flexi account to keep all of your designs and orders in one place.</p>
                <a class="btn btn-save" href="{% url 'profile:signin' %}">create an account</a>
            </div>
        </div>
    </div>

</div>

{% endblock %}

configurator/profiles/templates/profiles/profile.html
{% extends 'company/base.html' %}
{% block content %}

<div class="container" style="padding: 5%; padding-bottom: 15%;">
    
    <div class="container row">
        <div class="col-6" style="text-align: center;">
            <div class="container" style="text-align: left; padding-bottom: 3%;">
                <h3 class="h3" style="font-size: 32px;" >Your Profile</h3>
            </div>
            <div class="container" style="text-align: left;">
                    <div class="row">
                        <div class="col">
                            <p style="font-size: 20px;">Name</p>
                        </div>
                        <div class="col">
                            <p style="font-size: 20px;">{{name}}</p>
                        </div>
                    </div>
                    <div class="row"> 
                        <div class="col">
                            <p style="font-size: 20px;">Email</p>
                        </div>
                        <div class="col">
                            <p style="font-size: 20px;">{{user.email}}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <p style="font-size: 20px;">Address</p>
                        </div>
                        <div class="col">
                            <p style="font-size: 20px;">{{address}}</p>
                        </div>
                    </div>
            </div>
        </div>
        <div class="col-6" style="text-align: left; ">
            <ul style="padding-top: 13%;list-style-type: none;">
                <li>
                    <h4 ><a style='font-weight: 600; font-size: 30px; color: #7A9E7E;' href="{% url 'profile:drafts' %}">Drafts</a></h4>
                </li>
                <li>
                    <h4 ><a style='font-weight: 600; font-size: 30px; color: #7A9E7E;' href="{% url 'profile:log_out' %}">Logout</a></h4>
                </li>
            </ul>
        </div>
    </div>
</div>

{% endblock %}

configurator/profiles/templates/profiles/signin.html
{% extends 'company/base.html' %}
{% block content %}

<div class="container" style="padding: 5%;">
    <div class="container" style="text-align: left; padding-bottom: 3%;">
        <h2 class="h2" style="font-size: 32px;">Sign Up</h2>
    </div>
    <form action="{% url 'profile:signin' %}" method="post" name="signin" id="signin">
        <div class="container row">
            <div class="col-6" style="padding-right: 5%;">
                <div class="container" style="padding-right: 10%;">
                    <div class="form-group">
                        <label class="label" for="signin">E-Mail Adress</label>
                        <input type="text" class="form-control" id="login" name="email" placeholder="youremail@example.com" required>
                    </div>
                    <div class="form-group">
                        <label class="label" for="logsigninin">Username</label>
                        <input type="text" class="form-control" id="signin" name="username" placeholder="Username" required>
                    </div>
                    <div class="form-group">
                        <label class="label" for="signin">Password</label>
                        <input type="text" class="form-control" id="signin" name="password" placeholder="Password" required>
                    </div>
                </div>
            </div>
            <div class="col-6" style="padding-right: 5%;">
                <div class="form-group">
                    <label class="label" for="signin">First Name</label>
                    <input type="text" class="form-control" id="signin" name="name" placeholder="First name" required>
                </div>
                <div class="form-group">
                    <label class="label" for="logsigninin">Second Name</label>
                    <input type="text" class="form-control" id="signin" name="surname" placeholder="Second Name" required>
                </div>
                <div class="form-group">
                    <label class="label" for="signin">Address</label>
                    <input type="text" class="form-control" id="signin" name="address" placeholder="Address" required>
                </div>
            </div>
        </div>
        <div class="container row">
            <div class="col-12" style="text-align: center; padding-top: 5%;">
                <button type="submit" value="Submit" class="btn btn-save">sing up</button>
            </div>
        </div>
        </form>
    </div>

</div>

{% endblock %}